### ISSUE TITLE
Big file seek problems . 

### ISSUE THREAD

**Issue by GarfieldLinux** [portl4t/ts-mp4#3]
Hey  portl4t : 
   Here is an issue : 
         We take your ts-mp4 plugin for seeking mp4 video  and  get  problems now , just for the first seek video  with args "start=0" (test mp4 file1G  ATS not cached yet ) , Chrome(vlc mplayer ……) could not play the video until the ATS cached the big file(I can't believe that it takes a long time ) , So That's may be a bug , Can you spare some time to get it clear .  
   This plugin so cool . Thanks .

**Comment by portl4t** [comment]
Are you sure that your mp4 file has the index at the beginning of the file?

**Comment by GarfieldLinux** [comment]
Yes  .

**Comment by GarfieldLinux** [comment]
Hey portl4t:
   I think it's not your ts-mp4 plugin's problem , I changed  my mp4 player ,  problems  was gone ,  So issue should be closed . 
   Thanks .
